### ISSUE TITLE
Cant install on vagrant 1.9.1

### ISSUE THREAD

**Issue by matt-richardson** [Cimpress-MCP/vagrant-winrm-syncedfolders#10]
Running
```
$ vagrant plugin install vagrant-winrm-syncedfolders
```
on `macOS Sierra 10.12.1` gives an error:
```
Installing the 'vagrant-winrm-syncedfolders' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:2100:in `check_version_conflict': can't activate rubyntlm-0.4.0, already activated rubyntlm-0.6.1 (Gem::LoadError)
	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1276:in `activate'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:323:in `block in activate_solution'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:320:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:320:in `activate_solution'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:248:in `internal_install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:98:in `install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/manager.rb:62:in `block in install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/manager.rb:72:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/manager.rb:72:in `install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/action/install_gem.rb:37:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/command/base.rb:14:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/command/install.rb:32:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/command/install.rb:31:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/command/install.rb:31:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/command/root.rb:66:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/environment.rb:308:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/bin/vagrant:127:in `<main>'
```

Any ideas?

**Comment by kagarlickij** [comment]
I have exactly the same error, 
I'm running macOS 10.12.2 and packer 1.9.1

**Comment by kamlim1k** [comment]
Looks like dependency to winrm-fs should be updated
`spec.add_runtime_dependency "winrm-fs", "~> 0.3.0"`
After that it installs and running fine

**Comment by kagarlickij** [comment]
So any ideas about fixing this one?.. It happens to be rather critical..

**Comment by chrisbaldauf** [comment]
Hi all, sorry for the delay. I'm working on getting #9 out there, which I believe should solve the issue.

**Comment by chrisbaldauf** [comment]
@matt-richardson @kagarlickijd, please try version 1.0.1 published today.

```
$ vagrant -v
Vagrant 1.9.1
$ vagrant plugin install vagrant-winrm-syncedfolders
You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove this warning, install Vagrant using one of the
official packages from vagrantup.com.

Installing the 'vagrant-winrm-syncedfolders' plugin. This can take a few minutes...
Installed the plugin 'vagrant-winrm-syncedfolders (1.0.1)'!
```

Please let me know if that doesn't fix it.

**Comment by kagarlickij** [comment]
@chrisbaldauf thanks, it works for me

**Comment by matt-richardson** [comment]
Just got a chance to test it - works superbly. Thanks!
